version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  data: